services:
  db:
    image: postgres:16
    container_name: therapist_matcher_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: therapist_matcher
    ports:
      - "5432:5432"
    volumes:
      - therapist_matcher_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: therapist_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: therapist_api
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/therapist_matcher
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app

  dozzle:
    image: amir20/dozzle:latest
    container_name: therapist_dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  therapist_matcher_pgdata: